import { PrismaClient } from '@prisma/client';
import { addDays, format } from 'date-fns';
import dotenv from 'dotenv';

// Load environment variables
dotenv.config({ path: '.env.local' });
dotenv.config(); // Also try .env

const prisma = new PrismaClient();

// All demo events will have IDs starting with 'demo-' for easy removal
const DEMO_PREFIX = 'demo-';

async function main() {
  console.log('🌱 Starting database seed with demo events...');

  // Create venues (these are real Kingston venues, not demos)
  const venues = await Promise.all([
    prisma.venue.upsert({
      where: { id: 'venue-grand-theatre' },
      update: {},
      create: {
        id: 'venue-grand-theatre',
        name: 'The Grand Theatre',
        address: '218 Princess St, Kingston, ON',
        neighborhood: 'Downtown',
        website: 'https://kingstongrand.ca',
      },
    }),
    prisma.venue.upsert({
      where: { id: 'venue-ale-house' },
      update: {},
      create: {
        id: 'venue-ale-house',
        name: 'The Ale House',
        address: '393 Princess St, Kingston, ON',
        neighborhood: 'Downtown',
        website: 'https://alehousekingston.com',
      },
    }),
    prisma.venue.upsert({
      where: { id: 'venue-leons-centre' },
      update: {},
      create: {
        id: 'venue-leons-centre',
        name: "Leon's Centre",
        address: '1 The Tragically Hip Way, Kingston, ON',
        neighborhood: 'Downtown',
        website: 'https://leonscentre.com',
      },
    }),
    prisma.venue.upsert({
      where: { id: 'venue-toucan' },
      update: {},
      create: {
        id: 'venue-toucan',
        name: 'The Toucan',
        address: '76 Princess St, Kingston, ON',
        neighborhood: 'Downtown',
      },
    }),
    prisma.venue.upsert({
      where: { id: 'venue-tir-nan-og' },
      update: {},
      create: {
        id: 'venue-tir-nan-og',
        name: 'Tir Nan Og',
        address: '200 Ontario St, Kingston, ON',
        neighborhood: 'Waterfront',
      },
    }),
    prisma.venue.upsert({
      where: { id: 'venue-kbc' },
      update: {},
      create: {
        id: 'venue-kbc',
        name: 'Kingston Brewing Company',
        address: '34 Clarence St, Kingston, ON',
        neighborhood: 'Downtown',
      },
    }),
    prisma.venue.upsert({
      where: { id: 'venue-isabel' },
      update: {},
      create: {
        id: 'venue-isabel',
        name: 'Isabel Bader Centre',
        address: "390 King St W, Kingston, ON",
        neighborhood: "Queen's University",
        website: 'https://queensu.ca/theisabel',
      },
    }),
    prisma.venue.upsert({
      where: { id: 'venue-market-square' },
      update: {},
      create: {
        id: 'venue-market-square',
        name: 'Market Square',
        address: '216 Ontario St, Kingston, ON',
        neighborhood: 'Downtown',
      },
    }),
    prisma.venue.upsert({
      where: { id: 'venue-mansion' },
      update: {},
      create: {
        id: 'venue-mansion',
        name: 'The Mansion',
        address: '506 Princess St, Kingston, ON',
        neighborhood: 'Downtown',
      },
    }),
  ]);
  console.log(`✅ Created/updated ${venues.length} venues`);

  const today = new Date();

  // Helper to create demo event with categories
  async function createDemoEvent(
    id: string,
    data: {
      title: string;
      description: string;
      date: string;
      startTime: string;
      endTime?: string;
      venueId: string;
      categories: string[];
      price?: string;
      ticketUrl?: string;
      imageUrl?: string;
      featured?: boolean;
    }
  ) {
    const fullId = DEMO_PREFIX + id;
    
    // Delete existing if present
    await prisma.eventCategory.deleteMany({ where: { eventId: fullId } });
    await prisma.like.deleteMany({ where: { eventId: fullId } });
    await prisma.event.deleteMany({ where: { id: fullId } });
    
    const event = await prisma.event.create({
      data: {
        id: fullId,
        title: data.title,
        description: data.description,
        date: data.date,
        startTime: data.startTime,
        endTime: data.endTime,
        venueId: data.venueId,
        price: data.price,
        ticketUrl: data.ticketUrl,
        imageUrl: data.imageUrl,
        featured: data.featured || false,
        status: 'approved',
        categories: {
          create: data.categories.map((name) => ({ name })),
        },
      },
    });
    return event;
  }

  // Create demo events
  const events = await Promise.all([
    // Today's events (6 total: 3 events + 3 food deals)
    createDemoEvent('trivia-ale-house', {
      title: 'Trivia Night at The Ale House',
      description: "Test your knowledge at Kingston's most popular trivia night! Teams of up to 6 people. Prizes for top 3 teams. Great food and drink specials all night.",
      date: format(today, 'yyyy-MM-dd'),
      startTime: '19:00',
      endTime: '22:00',
      venueId: 'venue-ale-house',
      categories: ['trivia'],
      price: 'Free',
      imageUrl: 'https://images.unsplash.com/photo-1606092195730-5d7b9af1efc5?w=800',
    }),
    createDemoEvent('open-mic-kbc', {
      title: 'Open Mic Night',
      description: 'Bring your guitar, your voice, or your poetry! Sign-up starts at 7pm. All genres and skill levels welcome.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '20:00',
      endTime: '23:30',
      venueId: 'venue-kbc',
      categories: ['concert', 'nightlife'],
      price: 'Free',
      imageUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800',
    }),
    createDemoEvent('yoga-waterfront', {
      title: 'Sunset Yoga at the Waterfront',
      description: 'Join us for a relaxing evening yoga session overlooking Lake Ontario. All levels welcome. Bring your own mat.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '18:00',
      endTime: '19:00',
      venueId: 'venue-market-square',
      categories: ['workshop', 'community'],
      price: '$15',
      imageUrl: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800',
    }),
    createDemoEvent('live-jazz-mansion', {
      title: 'Live Jazz: The Blue Notes',
      description: 'Kingston\'s favorite jazz quartet performs classics and originals. Perfect backdrop for dinner and drinks.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '21:00',
      endTime: '00:00',
      venueId: 'venue-mansion',
      categories: ['concert', 'nightlife'],
      price: '$10',
      imageUrl: 'https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=800',
    }),
    createDemoEvent('comedy-night-grand', {
      title: 'Comedy Night at The Grand',
      description: 'Local comedians take the stage for a night of laughs! Featuring stand-up, improv, and audience participation. 19+ event.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '20:00',
      endTime: '23:00',
      venueId: 'venue-grand-theatre',
      categories: ['comedy', 'nightlife'],
      price: '$15',
      imageUrl: 'https://images.unsplash.com/photo-1501436513145-30f24e19fcc4?w=800',
    }),
    createDemoEvent('acrylic-workshop-isabel', {
      title: 'Evening Art Workshop',
      description: 'Learn to paint with acrylics! All materials provided. Perfect for beginners. Take home your masterpiece.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '18:30',
      endTime: '20:30',
      venueId: 'venue-isabel',
      categories: ['art', 'workshop'],
      price: '$25',
      imageUrl: 'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800',
    }),
    createDemoEvent('sports-watch-party', {
      title: 'Game Night Watch Party',
      description: 'Watch the big game on our giant screens! Special drink deals during the game. All sports fans welcome.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '19:00',
      endTime: '23:00',
      venueId: 'venue-ale-house',
      categories: ['sports', 'nightlife'],
      price: 'Free',
      imageUrl: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800',
    }),
    createDemoEvent('acoustic-session-tir', {
      title: 'Acoustic Sessions',
      description: 'Intimate acoustic performances by local singer-songwriters. Cozy atmosphere perfect for a relaxed evening.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '19:30',
      endTime: '22:30',
      venueId: 'venue-tir-nan-og',
      categories: ['live-music', 'concert'],
      price: 'Free',
      imageUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800',
    }),
    createDemoEvent('dance-class-market', {
      title: 'Evening Dance Class',
      description: 'Learn salsa dancing! No partner needed. All skill levels welcome. Great exercise and fun social activity.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '19:00',
      endTime: '20:30',
      venueId: 'venue-market-square',
      categories: ['activity', 'workshop'],
      price: '$12',
      imageUrl: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800',
    }),
    
    // Today's Food & Drink Specials (9 total)
    createDemoEvent('wings-wednesday', {
      title: 'Half-Price Wings Wednesday',
      description: 'All wings are half price every Wednesday! Choose from over 20 different sauces and dry rubs. Dine-in only.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '11:00',
      endTime: '23:00',
      venueId: 'venue-toucan',
      categories: ['food-deal'],
      price: 'Half-Price Wings',
    }),
    createDemoEvent('happy-hour-tir', {
      title: 'Happy Hour: $5 Pints',
      description: 'All draft beers just $5 during happy hour! Plus $2 off appetizers. The best special on the waterfront.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '16:00',
      endTime: '19:00',
      venueId: 'venue-tir-nan-og',
      categories: ['food-deal'],
      price: '$5 Pints',
    }),
    createDemoEvent('taco-tuesday', {
      title: '$3 Taco Tuesday',
      description: 'Every Tuesday, all tacos are just $3! Choose from beef, chicken, fish, or veggie. Margarita specials all day.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '11:00',
      endTime: '22:00',
      venueId: 'venue-ale-house',
      categories: ['food-deal'],
      price: '$3 Tacos',
    }),
    createDemoEvent('pizza-special', {
      title: 'Late Night Pizza Special',
      description: 'Half-price pizzas after 9pm! Perfect for post-show dining. Dine-in or takeout available.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '21:00',
      endTime: '01:00',
      venueId: 'venue-kbc',
      categories: ['food-deal'],
      price: '50% Off Pizza',
    }),
    createDemoEvent('kbc-burger-special', {
      title: 'Brewmaster Burger Deal',
      description: 'Our signature burger with a pint of house-brewed beer for just $15! Available all day. Choose from our selection of craft beers.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '11:00',
      endTime: '22:00',
      venueId: 'venue-kbc',
      categories: ['food-deal'],
      price: '$15 Burger & Pint',
    }),
    createDemoEvent('kbc-appetizer-hour', {
      title: 'Appetizer Hour Special',
      description: 'All appetizers are $8 during happy hour! Perfect for sharing. Try our famous nachos, wings, or loaded fries.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '15:00',
      endTime: '18:00',
      venueId: 'venue-kbc',
      categories: ['food-deal'],
      price: '$8 Appetizers',
    }),
    createDemoEvent('kbc-beer-flight', {
      title: 'Craft Beer Flight Deal',
      description: 'Sample 4 of our house-brewed beers for just $12! Get a taste of our seasonal brews and classic favorites.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '12:00',
      endTime: '23:00',
      venueId: 'venue-kbc',
      categories: ['food-deal'],
      price: '$12 Beer Flight',
    }),
    createDemoEvent('toucan-pint-special', {
      title: 'Pint of the Day',
      description: 'Our featured pint is just $6 all day! Rotating selection of local and craft beers. Ask your server for today\'s selection.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '11:00',
      endTime: '23:00',
      venueId: 'venue-toucan',
      categories: ['food-deal'],
      price: '$6 Pint',
    }),
    createDemoEvent('toucan-brunch-special', {
      title: 'Weekend Brunch Special',
      description: 'Brunch favorites with a side of home fries and toast. Includes coffee or tea. Available until 2pm.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '09:00',
      endTime: '14:00',
      venueId: 'venue-toucan',
      categories: ['food-deal'],
      price: '$12 Brunch',
    }),

    // Additional Today's Events (6 more)
    createDemoEvent('comedy-night-ale-house', {
      title: 'Comedy Night',
      description: 'Local comedians take the stage! Laughs guaranteed. 18+ event. Doors at 7pm, show at 8pm.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '20:00',
      endTime: '23:00',
      venueId: 'venue-ale-house',
      categories: ['nightlife', '19plus'],
      price: '$12',
      imageUrl: 'https://images.unsplash.com/photo-1508609349937-5ec4ae374ebf?w=800',
    }),
    createDemoEvent('art-workshop-isabel', {
      title: 'Watercolor Painting Workshop',
      description: 'Learn basic watercolor techniques in this beginner-friendly workshop. All materials provided. No experience needed!',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '14:00',
      endTime: '16:30',
      venueId: 'venue-isabel',
      categories: ['workshop', 'community'],
      price: '$25',
      imageUrl: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800',
    }),
    createDemoEvent('dance-class-market-square', {
      title: 'Latin Dance Class',
      description: 'Learn salsa and bachata in this fun, energetic class. No partner needed. All skill levels welcome.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '19:00',
      endTime: '20:30',
      venueId: 'venue-market-square',
      categories: ['workshop', 'community'],
      price: '$15',
      imageUrl: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800',
    }),
    createDemoEvent('acoustic-night-toucan', {
      title: 'Acoustic Sessions',
      description: 'Intimate acoustic performances from local singer-songwriters. Cozy atmosphere perfect for listening.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '20:30',
      endTime: '23:00',
      venueId: 'venue-toucan',
      categories: ['live-music', 'nightlife'],
      price: 'Free',
      imageUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800',
    }),
    createDemoEvent('karaoke-night-kbc', {
      title: 'Karaoke Night',
      description: 'Grab the mic and sing your heart out! Thousands of songs to choose from. Prizes for best performances.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '21:00',
      endTime: '01:00',
      venueId: 'venue-kbc',
      categories: ['nightlife', 'community'],
      price: 'Free',
      imageUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800',
    }),
    createDemoEvent('poetry-reading-mansion', {
      title: 'Poetry Reading Night',
      description: 'Local poets share their work in this intimate setting. Open mic slots available. Come listen or share your own!',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '19:30',
      endTime: '21:30',
      venueId: 'venue-mansion',
      categories: ['community', 'workshop'],
      price: 'Free',
      imageUrl: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800',
    }),
    // 9 More Events for Today
    createDemoEvent('rock-band-mansion', {
      title: 'Rock Night: The Electric Souls',
      description: 'High-energy rock band performing classic hits and original songs. Guaranteed to get you moving!',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '22:00',
      endTime: '01:00',
      venueId: 'venue-mansion',
      categories: ['concert', 'nightlife'],
      price: '$8',
      imageUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800',
    }),
    createDemoEvent('board-game-night-kbc', {
      title: 'Board Game Night',
      description: 'Bring your friends for an evening of board games! We have hundreds of games available. Great for groups.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '18:00',
      endTime: '23:00',
      venueId: 'venue-kbc',
      categories: ['community', 'activity-nights'],
      price: 'Free',
      imageUrl: 'https://images.unsplash.com/photo-1606166188510-c6af6e7cbb89?w=800',
    }),
    createDemoEvent('basketball-tournament', {
      title: '3v3 Basketball Tournament',
      description: 'Competitive 3-on-3 basketball tournament. Registration required. Prizes for winners. All skill levels welcome.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '10:00',
      endTime: '16:00',
      venueId: 'venue-market-square',
      categories: ['sports', 'activity'],
      price: '$20 per team',
      imageUrl: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800',
    }),
    createDemoEvent('cooking-class-isabel', {
      title: 'Cooking Class: Pasta Making',
      description: 'Learn to make fresh pasta from scratch! Includes hands-on instruction and dinner. All skill levels welcome.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '17:00',
      endTime: '20:00',
      venueId: 'venue-isabel',
      categories: ['workshop', 'community'],
      price: '$45',
      imageUrl: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=800',
    }),
    createDemoEvent('dj-night-toucan', {
      title: 'DJ Night: Electronic Vibes',
      description: 'Local DJ spins the best electronic and dance music all night long. Full bar service available.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '22:00',
      endTime: '02:00',
      venueId: 'venue-toucan',
      categories: ['nightlife', 'live-music'],
      price: '$5',
      imageUrl: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800',
    }),
    createDemoEvent('book-club-mansion', {
      title: 'Book Club Meeting',
      description: 'Monthly book club discussion. This month we\'re discussing "The Great Gatsby". All readers welcome!',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '18:30',
      endTime: '20:30',
      venueId: 'venue-mansion',
      categories: ['community', 'workshop'],
      price: 'Free',
      imageUrl: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800',
    }),
    createDemoEvent('martial-arts-demo', {
      title: 'Martial Arts Demonstration',
      description: 'Watch skilled martial artists demonstrate various techniques. Free class trial available after the demo.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '15:00',
      endTime: '17:00',
      venueId: 'venue-market-square',
      categories: ['sports', 'community'],
      price: 'Free',
      imageUrl: 'https://images.unsplash.com/photo-1547153760-18fc86324498?w=800',
    }),
    createDemoEvent('folk-music-tir', {
      title: 'Folk Music Night',
      description: 'Local folk musicians perform acoustic sets featuring traditional and contemporary folk music.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '20:00',
      endTime: '23:00',
      venueId: 'venue-tir-nan-og',
      categories: ['live-music', 'concert'],
      price: 'Free',
      imageUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800',
    }),
    createDemoEvent('theatre-workshop-isabel', {
      title: 'Improv Theatre Workshop',
      description: 'Learn the basics of improvisational theatre! Fun, interactive class perfect for beginners. No experience needed.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '19:00',
      endTime: '21:00',
      venueId: 'venue-isabel',
      categories: ['workshop', 'theatre'],
      price: '$20',
      imageUrl: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800',
    }),

    // 9 More Events for Today
    createDemoEvent('blues-night-grand', {
      title: 'Blues Night: The Delta Kings',
      description: 'Authentic blues music from one of Kingston\'s premier blues bands. Get ready for soulful guitar solos and powerful vocals.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '20:30',
      endTime: '23:30',
      venueId: 'venue-grand-theatre',
      categories: ['concert', 'live-music'],
      price: '$12',
      imageUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800',
    }),
    createDemoEvent('yoga-morning-market', {
      title: 'Morning Yoga Flow',
      description: 'Start your day with an energizing yoga flow class. Suitable for all levels. Bring your own mat and water bottle.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '08:00',
      endTime: '09:00',
      venueId: 'venue-market-square',
      categories: ['workshop', 'daytime'],
      price: '$10',
      imageUrl: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800',
    }),
    createDemoEvent('photography-walk', {
      title: 'Photography Walk: Downtown Kingston',
      description: 'Join us for a guided photography walk through historic downtown Kingston. Learn composition techniques while capturing beautiful architecture.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '14:00',
      endTime: '16:00',
      venueId: 'venue-market-square',
      categories: ['workshop', 'daytime'],
      price: '$20',
      imageUrl: 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800',
    }),
    createDemoEvent('indie-pop-concert', {
      title: 'Indie Pop Showcase',
      description: 'Three up-and-coming indie pop bands share the stage for an evening of catchy melodies and infectious energy.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '19:00',
      endTime: '23:00',
      venueId: 'venue-mansion',
      categories: ['concert', 'nightlife'],
      price: '$15',
      imageUrl: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800',
    }),
    createDemoEvent('meditation-session', {
      title: 'Evening Meditation Session',
      description: 'Unwind with a guided meditation session. Perfect for reducing stress and finding inner peace. All experience levels welcome.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '19:30',
      endTime: '20:30',
      venueId: 'venue-isabel',
      categories: ['workshop', 'community'],
      price: '$12',
      imageUrl: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800',
    }),
    createDemoEvent('country-music-night', {
      title: 'Country Music Night',
      description: 'Live country music featuring local and touring artists. Line dancing lessons available. Boots and hats encouraged!',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '20:00',
      endTime: '01:00',
      venueId: 'venue-ale-house',
      categories: ['live-music', 'nightlife'],
      price: '$8',
      imageUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800',
    }),
    createDemoEvent('writing-workshop', {
      title: 'Creative Writing Workshop',
      description: 'Explore your creativity in this supportive writing workshop. Bring a notebook and pen. Prompts and exercises provided.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '18:00',
      endTime: '20:00',
      venueId: 'venue-mansion',
      categories: ['workshop', 'community'],
      price: '$15',
      imageUrl: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800',
    }),
    createDemoEvent('fitness-bootcamp', {
      title: 'Outdoor Fitness Bootcamp',
      description: 'High-intensity outdoor workout session. All fitness levels welcome. Bring water and a towel. Meet at the waterfront.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '17:00',
      endTime: '18:00',
      venueId: 'venue-market-square',
      categories: ['sports', 'activity-nights'],
      price: '$10',
      imageUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800',
    }),
    createDemoEvent('classical-recital', {
      title: 'Classical Piano Recital',
      description: 'An intimate evening of classical piano music featuring works by Chopin, Debussy, and contemporary composers.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '19:00',
      endTime: '20:30',
      venueId: 'venue-isabel',
      categories: ['concert', 'theatre'],
      price: '$18',
      imageUrl: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=800',
    }),

    // 9 More Daily Specials for Today
    createDemoEvent('mansion-wine-wednesday', {
      title: 'Wine Wednesday Special',
      description: 'Half-price bottles of wine all day! Choose from our curated selection of reds, whites, and rosés. Perfect for date night.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '11:00',
      endTime: '23:00',
      venueId: 'venue-mansion',
      categories: ['food-deal'],
      price: '50% Off Wine',
    }),
    createDemoEvent('grand-appetizer-special', {
      title: 'Appetizer Platter Deal',
      description: 'Share a platter of our best appetizers for just $18! Includes wings, nachos, and spring rolls. Great for groups.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '16:00',
      endTime: '22:00',
      venueId: 'venue-grand-theatre',
      categories: ['food-deal'],
      price: '$18 Platter',
    }),
    createDemoEvent('ale-house-pitcher-special', {
      title: 'Pitcher Special: $12',
      description: 'Any draft beer pitcher for just $12! Available all day. Perfect for sharing with friends. Dine-in only.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '11:00',
      endTime: '23:00',
      venueId: 'venue-ale-house',
      categories: ['food-deal'],
      price: '$12 Pitchers',
    }),
    createDemoEvent('tir-nan-og-fish-fry', {
      title: 'Fish & Chips Friday Special',
      description: 'Traditional fish and chips with a side of coleslaw for just $14! Fresh, beer-battered cod. Available all day.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '11:00',
      endTime: '22:00',
      venueId: 'venue-tir-nan-og',
      categories: ['food-deal'],
      price: '$14 Fish & Chips',
    }),
    createDemoEvent('kbc-pizza-monday', {
      title: 'Pizza & Pint Combo',
      description: 'Personal pizza with a pint of house beer for $16! Choose from our selection of specialty pizzas. Great value!',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '12:00',
      endTime: '21:00',
      venueId: 'venue-kbc',
      categories: ['food-deal'],
      price: '$16 Pizza & Pint',
    }),
    createDemoEvent('toucan-lunch-special', {
      title: 'Lunch Combo Deal',
      description: 'Soup, sandwich, and a drink for just $12! Available from 11am to 3pm. Perfect for a quick, satisfying lunch.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '11:00',
      endTime: '15:00',
      venueId: 'venue-toucan',
      categories: ['food-deal'],
      price: '$12 Lunch Combo',
    }),
    createDemoEvent('mansion-dessert-night', {
      title: 'Dessert Night Special',
      description: 'All desserts are 20% off after 8pm! Indulge in our homemade cheesecake, brownies, or ice cream sundaes.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '20:00',
      endTime: '23:00',
      venueId: 'venue-mansion',
      categories: ['food-deal'],
      price: '20% Off Desserts',
    }),
    createDemoEvent('ale-house-breakfast', {
      title: 'Breakfast Special',
      description: 'Full breakfast with eggs, bacon, toast, and coffee for just $8! Available until 11am. Start your day right.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '07:00',
      endTime: '11:00',
      venueId: 'venue-ale-house',
      categories: ['food-deal'],
      price: '$8 Breakfast',
    }),
    createDemoEvent('tir-nan-og-cocktail-hour', {
      title: 'Cocktail Hour: $8 Drinks',
      description: 'All signature cocktails just $8 during happy hour! Try our seasonal specials and classic favorites.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '17:00',
      endTime: '19:00',
      venueId: 'venue-tir-nan-og',
      categories: ['food-deal'],
      price: '$8 Cocktails',
    }),

    // 9 More Events for Today
    createDemoEvent('punk-rock-show', {
      title: 'Punk Rock Night: The Rebels',
      description: 'High-energy punk rock show featuring local and touring bands. Mosh pit encouraged! 19+ event.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '21:00',
      endTime: '01:00',
      venueId: 'venue-mansion',
      categories: ['concert', 'nightlife'],
      price: '$10',
      imageUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800',
    }),
    createDemoEvent('pottery-workshop', {
      title: 'Pottery Workshop: Hand Building',
      description: 'Learn the basics of hand-building pottery. Create your own bowl or vase! All materials and firing included.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '16:00',
      endTime: '18:30',
      venueId: 'venue-isabel',
      categories: ['workshop', 'art'],
      price: '$35',
      imageUrl: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800',
    }),
    createDemoEvent('running-club', {
      title: 'Evening Running Club',
      description: 'Join our weekly running group! Routes vary between 5K and 10K. All paces welcome. Meet at the waterfront.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '18:00',
      endTime: '19:30',
      venueId: 'venue-market-square',
      categories: ['sports', 'activity-nights'],
      price: 'Free',
      imageUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800',
    }),
    createDemoEvent('r-and-b-night', {
      title: 'R&B Soul Night',
      description: 'Smooth R&B and soul music all night long. Perfect for dancing or just relaxing with great music.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '21:30',
      endTime: '01:00',
      venueId: 'venue-toucan',
      categories: ['live-music', 'nightlife'],
      price: '$7',
      imageUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800',
    }),
    createDemoEvent('chess-tournament', {
      title: 'Chess Tournament',
      description: 'Competitive chess tournament with prizes for top finishers. All skill levels welcome. Registration required.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '14:00',
      endTime: '18:00',
      venueId: 'venue-kbc',
      categories: ['activity', 'community'],
      price: '$10 entry',
      imageUrl: 'https://images.unsplash.com/photo-1529699211952-734e80c4d42b?w=800',
    }),
    createDemoEvent('spoken-word-night', {
      title: 'Spoken Word Poetry Night',
      description: 'Local poets and storytellers share their work. Open mic slots available. Powerful and moving performances.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '19:00',
      endTime: '21:00',
      venueId: 'venue-grand-theatre',
      categories: ['community', 'workshop'],
      price: '$8',
      imageUrl: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800',
    }),
    createDemoEvent('rock-climbing-session', {
      title: 'Indoor Rock Climbing',
      description: 'Try indoor rock climbing! Equipment rental included. Experienced instructors available. All levels welcome.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '15:00',
      endTime: '18:00',
      venueId: 'venue-market-square',
      categories: ['sports', 'activity'],
      price: '$20',
      imageUrl: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800',
    }),
    createDemoEvent('folk-rock-concert', {
      title: 'Folk Rock Showcase',
      description: 'Blend of folk and rock music from talented local artists. Intimate setting perfect for music lovers.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '20:00',
      endTime: '23:00',
      venueId: 'venue-ale-house',
      categories: ['live-music', 'concert'],
      price: '$10',
      imageUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800',
    }),
    createDemoEvent('coding-workshop', {
      title: 'Beginner Coding Workshop',
      description: 'Learn the basics of web development! No experience needed. Bring your laptop. Introduction to HTML, CSS, and JavaScript.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '18:30',
      endTime: '21:00',
      venueId: 'venue-isabel',
      categories: ['workshop', 'community'],
      price: '$30',
      imageUrl: 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=800',
    }),

    // 9 More Daily Specials for Today
    createDemoEvent('grand-happy-hour-extended', {
      title: 'Extended Happy Hour',
      description: 'All drinks and appetizers are 25% off during our extended happy hour! Perfect for after-work relaxation.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '15:00',
      endTime: '20:00',
      venueId: 'venue-grand-theatre',
      categories: ['food-deal'],
      price: '25% Off',
    }),
    createDemoEvent('ale-house-steak-night', {
      title: 'Steak Night Special',
      description: '8oz sirloin steak with sides for just $18! Available after 5pm. Cooked to your preference.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '17:00',
      endTime: '22:00',
      venueId: 'venue-ale-house',
      categories: ['food-deal'],
      price: '$18 Steak Dinner',
    }),
    createDemoEvent('tir-nan-og-pasta-night', {
      title: 'Pasta Night: All You Can Eat',
      description: 'All-you-can-eat pasta bar with multiple sauce options for $15! Includes salad and bread. Available all evening.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '17:00',
      endTime: '21:00',
      venueId: 'venue-tir-nan-og',
      categories: ['food-deal'],
      price: '$15 Pasta',
    }),
    createDemoEvent('kbc-wing-wednesday', {
      title: 'Wing Wednesday: $0.50 Wings',
      description: 'All wings just 50 cents each! Choose from 15 different sauces. Minimum order of 10 wings. Dine-in only.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '11:00',
      endTime: '23:00',
      venueId: 'venue-kbc',
      categories: ['food-deal'],
      price: '$0.50/Wing',
    }),
    createDemoEvent('toucan-margarita-monday', {
      title: 'Margarita Monday Special',
      description: 'All margaritas are $7 all day! Try our classic, frozen, or flavored options. Perfect way to start the week.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '11:00',
      endTime: '23:00',
      venueId: 'venue-toucan',
      categories: ['food-deal'],
      price: '$7 Margaritas',
    }),
    createDemoEvent('mansion-sushi-night', {
      title: 'Sushi Night Special',
      description: 'Fresh sushi rolls and sashimi at special prices! Choose from our chef\'s selection or build your own combo.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '18:00',
      endTime: '22:00',
      venueId: 'venue-mansion',
      categories: ['food-deal'],
      price: 'Sushi Specials',
    }),
    createDemoEvent('grand-dessert-bar', {
      title: 'Dessert Bar: $5 Sweets',
      description: 'All desserts from our dessert bar are just $5! Includes cakes, pies, and seasonal treats. After 7pm only.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '19:00',
      endTime: '23:00',
      venueId: 'venue-grand-theatre',
      categories: ['food-deal'],
      price: '$5 Desserts',
    }),
    createDemoEvent('ale-house-breakfast-burrito', {
      title: 'Breakfast Burrito Deal',
      description: 'Loaded breakfast burrito with eggs, bacon, cheese, and potatoes for just $9! Available until 11am.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '07:00',
      endTime: '11:00',
      venueId: 'venue-ale-house',
      categories: ['food-deal'],
      price: '$9 Burrito',
    }),
    createDemoEvent('tir-nan-og-beer-tasting', {
      title: 'Beer Tasting Flight',
      description: 'Sample 6 different craft beers for $14! Includes tasting notes and recommendations from our brewmaster.',
      date: format(today, 'yyyy-MM-dd'),
      startTime: '12:00',
      endTime: '23:00',
      venueId: 'venue-tir-nan-og',
      categories: ['food-deal'],
      price: '$14 Flight',
    }),

    // Tomorrow
    createDemoEvent('symphony-holiday', {
      title: 'Kingston Symphony: Holiday Classics',
      description: 'Join the Kingston Symphony for an evening of beloved holiday classics. Featuring works by Tchaikovsky, Handel, and traditional carols arranged for full orchestra.',
      date: format(addDays(today, 1), 'yyyy-MM-dd'),
      startTime: '19:30',
      endTime: '21:30',
      venueId: 'venue-grand-theatre',
      categories: ['concert', 'theatre'],
      price: '$35-75',
      ticketUrl: 'https://kingstongrand.ca',
      imageUrl: 'https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=800',
      featured: true,
    }),
    createDemoEvent('burger-night', {
      title: '$5 Burger Night',
      description: 'Every Thursday, enjoy our famous half-pound burgers for just $5. Add fries for $2 more. While supplies last!',
      date: format(addDays(today, 1), 'yyyy-MM-dd'),
      startTime: '17:00',
      endTime: '21:00',
      venueId: 'venue-tir-nan-og',
      categories: ['food-deal'],
      price: '$5 Burgers',
    }),

    // This weekend
    createDemoEvent('frontenacs-game', {
      title: "Kingston Frontenacs vs Ottawa 67's",
      description: "OHL hockey action as the Frontenacs take on the Ottawa 67's. Family-friendly atmosphere with activities for kids between periods.",
      date: format(addDays(today, 2), 'yyyy-MM-dd'),
      startTime: '19:00',
      endTime: '22:00',
      venueId: 'venue-leons-centre',
      categories: ['sports', 'family'],
      price: '$18-45',
      ticketUrl: 'https://leonscentre.com',
      imageUrl: 'https://images.unsplash.com/photo-1515703407324-5f753afd8be8?w=800',
      featured: true,
    }),
    createDemoEvent('farmers-market', {
      title: 'Saturday Farmers Market',
      description: 'Fresh local produce, artisan goods, baked treats, and more from over 50 local vendors. Live music and family activities.',
      date: format(addDays(today, 2), 'yyyy-MM-dd'),
      startTime: '09:00',
      endTime: '14:00',
      venueId: 'venue-market-square',
      categories: ['market', 'family', 'community'],
      price: 'Free Admission',
      imageUrl: 'https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=800',
      featured: true,
    }),
    createDemoEvent('indie-rock-night', {
      title: 'Indie Rock Night: The Wilderness',
      description: 'Toronto-based indie rock band The Wilderness brings their energetic live show to Kingston. Opening act: local favorites Shoreline.',
      date: format(addDays(today, 2), 'yyyy-MM-dd'),
      startTime: '21:00',
      endTime: '01:00',
      venueId: 'venue-mansion',
      categories: ['concert', 'nightlife'],
      price: '$15',
      imageUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800',
    }),

    // Next week
    createDemoEvent('paint-night', {
      title: 'Paint Night: Winter Wonderland',
      description: 'Create your own winter scene masterpiece! All supplies included. No experience necessary. Wine and snacks available for purchase.',
      date: format(addDays(today, 4), 'yyyy-MM-dd'),
      startTime: '18:30',
      endTime: '21:00',
      venueId: 'venue-kbc',
      categories: ['workshop', 'nightlife'],
      price: '$45',
      imageUrl: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=800',
    }),
    createDemoEvent('comedy-night', {
      title: 'Comedy Night: Stand-Up Showcase',
      description: "Laugh the night away with five of Canada's funniest up-and-coming comedians. Hosted by Kingston's own Mike Patterson.",
      date: format(addDays(today, 5), 'yyyy-MM-dd'),
      startTime: '20:00',
      endTime: '22:30',
      venueId: 'venue-grand-theatre',
      categories: ['theatre', 'nightlife'],
      price: '$25',
      imageUrl: 'https://images.unsplash.com/photo-1527224538127-2104bb71c51b?w=800',
    }),
    createDemoEvent('jazz-brunch', {
      title: 'Jazz Brunch',
      description: 'Start your Sunday right with live jazz, bottomless mimosas, and a delicious brunch buffet. Reservations recommended.',
      date: format(addDays(today, 3), 'yyyy-MM-dd'),
      startTime: '10:00',
      endTime: '14:00',
      venueId: 'venue-tir-nan-og',
      categories: ['concert', 'food-deal'],
      price: '$35',
      imageUrl: 'https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=800',
    }),
    createDemoEvent('kids-art', {
      title: "Kids' Art Workshop",
      description: 'Creative art workshop for children ages 6-12. This week: making holiday ornaments! All materials provided.',
      date: format(addDays(today, 6), 'yyyy-MM-dd'),
      startTime: '14:00',
      endTime: '16:00',
      venueId: 'venue-market-square',
      categories: ['workshop', 'family'],
      price: '$15',
    }),
    createDemoEvent('chamber-music', {
      title: 'Chamber Music Concert',
      description: 'An intimate evening of chamber music featuring works by Mozart, Beethoven, and contemporary Canadian composers.',
      date: format(addDays(today, 7), 'yyyy-MM-dd'),
      startTime: '19:30',
      endTime: '21:00',
      venueId: 'venue-isabel',
      categories: ['concert'],
      price: '$20-40',
      imageUrl: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=800',
      featured: true,
    }),
    createDemoEvent('pub-quiz-championship', {
      title: 'Pub Quiz Championship',
      description: 'Monthly championship round! Top teams from weekly trivia nights compete for prizes and bragging rights.',
      date: format(addDays(today, 8), 'yyyy-MM-dd'),
      startTime: '19:00',
      endTime: '22:00',
      venueId: 'venue-ale-house',
      categories: ['trivia'],
      price: 'Free',
    }),
    createDemoEvent('winter-festival', {
      title: 'Winter Festival',
      description: 'Annual winter celebration featuring ice sculptures, hot chocolate, skating, and holiday market. Fun for the whole family!',
      date: format(addDays(today, 10), 'yyyy-MM-dd'),
      startTime: '11:00',
      endTime: '20:00',
      venueId: 'venue-market-square',
      categories: ['festival', 'family', 'community'],
      price: 'Free',
      featured: true,
    }),
  ]);

  console.log(`✅ Created ${events.length} demo events`);
  console.log('🎉 Database seeding completed!');
  console.log('');
  console.log('💡 To remove demo events, run: npm run db:clear-demos');
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
